# Generated by Django 3.1.1 on 2020-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('WEIGHT', models.CharField(max_length=80)),
                ('OZ', models.FloatField()),
                ('PRICE_TEXT', models.CharField(max_length=20)),
                ('PRICE', models.FloatField()),
                ('PRICE_PER_OZ', models.FloatField()),
                ('CURRENCY', models.CharField(max_length=10)),
                ('AVAILABILITY', models.CharField(max_length=100)),
                ('LINK', models.CharField(max_length=300)),
                ('LOAD_TIME', models.CharField(max_length=30)),
                ('SHOP', models.CharField(max_length=40)),
            ],
        ),
    ]
