# Generated by Django 3.1.1 on 2020-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricenew',
            name='IMG_LINK',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
