# Generated by Django 3.1.1 on 2020-09-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0003_v_pricenew'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v_pricenew',
            table='compare_app_v_pricenew',
        ),
    ]
