# Generated by Django 3.1.1 on 2020-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0005_pricenew_metal'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUR', models.FloatField()),
                ('LOAD_TIME', models.CharField(max_length=30)),
            ],
        ),
    ]
