# Generated by Django 3.1.1 on 2020-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0006_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricenew',
            name='PRICE_PER_OZ',
            field=models.CharField(max_length=5),
        ),
    ]
