# Generated by Django 3.1.1 on 2020-09-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0008_auto_20200928_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricenew',
            new_name='Prices',
        ),
    ]
