# Generated by Django 3.1.1 on 2020-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0013_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pricing',
        ),
    ]
