# Generated by Django 3.1.1 on 2020-09-28 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0014_delete_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='EUR',
            new_name='VALUE',
        ),
        migrations.AddField(
            model_name='currency',
            name='CURRENCY',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
