# Generated by Django 3.1.1 on 2020-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0015_auto_20200928_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='CURRENCY',
        ),
        migrations.AddField(
            model_name='currency',
            name='CURRENCY_CODE',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
