# Generated by Django 3.1.1 on 2020-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0016_auto_20200928_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.FloatField()),
                ('LOAD_TIME', models.CharField(max_length=30)),
                ('CURRENCY_CODE', models.CharField(max_length=20)),
            ],
        ),
    ]
