# Generated by Django 3.1.1 on 2020-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0017_currencies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currency',
        ),
    ]
