# Generated by Django 3.1.1 on 2020-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0018_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricings',
            name='PRICE_PER_OZ_PLN',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricings',
            name='PRICE_PLN',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
