# Generated by Django 3.1.1 on 2020-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0020_v_pricenew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricings',
            name='PRICE_PLN',
            field=models.CharField(max_length=20),
        ),
    ]
